SELECT
    ID AS COA_CODE,
    BUDGET_NAME AS DESCRIPTION,
    UPDATED_AT AS END_DATE,
    CASE
        WHEN UPDATED_AT IS NOT NULL THEN 'U'
        ELSE 'C'
    END AS ACTION_TYPE
FROM BUDGETS
UNION
SELECT
    ID AS COA_CODE,
    NATIONAL_STRATEGY AS DESCRIPTION,
    UPDATED_AT AS END_DATE,
    CASE
        WHEN UPDATED_AT IS NOT NULL THEN 'U'
        ELSE 'C'
    END AS ACTION_TYPE
FROM national_strategies
UNION
SELECT
    LIST_EXPENSES_ID AS COA_CODE,
    LIST_EXPENSES_NAME AS DESCRIPTION,
    UPDATED_AT AS END_DATE,
    CASE
        WHEN UPDATED_AT IS NOT NULL THEN 'U'
        ELSE 'C'
    END AS ACTION_TYPE
FROM list_expenses